feat: 适配deepin-boot-kit工具,仓库版本与回滚调用由此工具管理
1.修改版本号获取逻辑,由deepin-boot-kit工具进行生成
2.删除grub生成逻辑,grub由deepin-boot-kit工具进行管理
3.增加bootlist接口,提供deepin-boot-kit工具使其生成对应的grub列表
4.deepin-boot-kit代码合入至deepin-upgrade-manager中
5.删除获取commitid接口,改为由version删除对应版本号

Bug: 适配deepin-boot-kit工具,仓库版本与回滚调用由此工具管理
Task: https://pms.uniontech.com/task-view-162237.html
Change-Id: I4e77ab3ffc5faf223c410680a6de3f38ab1685bf

diff --git a/cmd/grub.d/sw/15_deepin-boot-kit b/cmd/grub.d/sw/15_deepin-boot-kit
--- a/cmd/grub.d/sw/15_deepin-boot-kit
+++ b/cmd/grub.d/sw/15_deepin-boot-kit
@@ -13,12 +13,16 @@ boot_device_id=$GRUB_DEVICE_UUID
 
 LINUX_ROOT_DEVICE=UUID=${GRUB_DEVICE_UUID}
 
-UPGRADER=/usr/sbin/deepin-upgrade-manager
+ATOMIC=atomic
+
+UPGRADER=/usr/sbin/deepin-boot-kit
+ATOMIC_UPGRADE=/usr/sbin/deepin-upgrade-manager
+
 SNAPSHOT_DIR_PREFIX=/boot/snapshot
 SNAPSHOT_DIR=/snapshot
 
 if [ "x${DEEPIN_UPGRADER_VERSION_LIMIT}" = "x" ]; then
-    DEEPIN_UPGRADER_VERSION_LIMIT=3
+    DEEPIN_UPGRADER_VERSION_LIMIT=10
 fi
 
 if [ ! -f ${UPGRADER} ];then
@@ -31,9 +35,6 @@ while read line
 do
     echo "# will parse: ${line}"
     case "$line" in
-        "ActiveVersion"*)
-            activeVersion=$(echo $line | awk -F ':' '{print $2}' | awk '{gsub(/^\s+|\s+$/, "");print}')
-            ;;
         "AvailVersionList"*)
             availList=$(echo $line | awk -F ':' '{print $2}' | awk '{gsub(/^\s+|\s+$/, "");print}')
             availList=(${availList// / })
@@ -60,16 +61,22 @@ do
     if [ $offset -ge $limit ];then
         break
     fi
-
+    type=""
     if [ ! -d "${SNAPSHOT_DIR_PREFIX}/${ver}" ]; then
-        echo "# not exists: ${SNAPSHOT_DIR_PREFIX}/${ver}, generated by: ${UPGRADER} --action=snapshot --version=${ver}"
-        ${UPGRADER} --action=snapshot --version=${ver}
+        type=`${UPGRADER} --action=type --version=${ver}`
         if [ "$?" != "0" ]; then
             continue
         fi
+        if [ "${ATOMIC}" = "${type}" ]; then
+            ${ATOMIC_UPGRADE} --action=snapshot --version=${ver}
+            if [ "$?" != "0" ]; then
+                continue
+            fi
+        fi
+
     fi
 
-    rollbackList[${offset}]=${ver}
+    rollbackList[${offset}]="${ver}"
     offset=$((1+${offset}))
 done
 
@@ -169,6 +176,100 @@ EOF
 EOF
 }
 
+get_vmlinux_initrd()
+{
+    linux="$1"
+    basename=`basename $linux`
+    dirname=`dirname $linux`
+    dtbo_dirname=`dirname $dirname`
+    dtbo_rel_dirname=`make_system_path_relative_to_its_root $dtbo_dirname`
+
+    rel_dirname=`make_system_path_relative_to_its_root $dirname`
+    version=`echo $basename | sed -e "s,^[^0-9]*-,,g"`
+    alt_version=`echo $version | sed -e "s,\.old$,,g"`
+    if test -e "$dtbo_dirname/dtbo.img"; then
+	    dtbo=1
+    fi
+
+    INITRD=
+    if test -e "${SNAPSHOT_DIR}/initrd.img-${version}"; then
+	    INITRD="${rel_dirname}/initrd.img-${version}"
+    elif  test -e "${SNAPSHOT_DIR}/initrd.img-${alt_version}";then
+        INITRD="${rel_dirname}/initrd.img-${alt_version}"
+    fi
+    LINUX=${rel_dirname}/${basename}
+}
+
+machine=`uname -m`
+case "x$machine" in
+    xi?86 | xx86_64)
+	list=
+	for i in /boot/vmlinuz-* /vmlinuz-* /boot/kernel-* ; do
+	    if grub_file_is_not_garbage "$i" ; then list="$list $i" ; fi
+	done ;;
+    *)
+	list=
+	for i in /boot/vmlinuz-* /boot/vmlinux-* /vmlinuz-* /vmlinux-* /boot/kernel-* ; do
+                  if grub_file_is_not_garbage "$i" ; then list="$list $i" ; fi
+	done ;;
+esac
+
+get_default_vmlinux_initrd()
+{
+while [ "x$list" != "x" ] ; do
+  linux=`version_find_latest $list`
+  case $linux in
+    *.efi.signed)
+      # We handle these in linux_entry.
+      list=`echo $list | tr ' ' '\n' | grep -vx $linux | tr '\n' ' '`
+      continue
+      ;;
+  esac
+  basename=`basename $linux`
+  dirname=`dirname $linux`
+  rel_dirname=`make_system_path_relative_to_its_root $dirname`
+  version=`echo $basename | sed -e "s,^[^0-9]*-,,g"`
+  alt_version=`echo $version | sed -e "s,\.old$,,g"`
+  linux_root_device_thisversion="${LINUX_ROOT_DEVICE}"
+
+  initrd_early=
+  for i in ${GRUB_EARLY_INITRD_LINUX_STOCK} \
+	   ${GRUB_EARLY_INITRD_LINUX_CUSTOM}; do
+    if test -e "${dirname}/${i}" ; then
+      initrd_early="${initrd_early} ${i}"
+    fi
+  done
+
+  INITRD=
+  for i in "initrd.img-${version}" "initrd-${version}.img" "initrd-${version}.gz" \
+	   "initrd-${version}" "initramfs-${version}.img" \
+	   "initrd.img-${alt_version}" "initrd-${alt_version}.img" \
+	   "initrd-${alt_version}" "initramfs-${alt_version}.img" \
+	   "initramfs-genkernel-${version}" \
+	   "initramfs-genkernel-${alt_version}" \
+	   "initramfs-genkernel-${GENKERNEL_ARCH}-${version}" \
+	   "initramfs-genkernel-${GENKERNEL_ARCH}-${alt_version}"; do
+    if test -e "${dirname}/${i}" ; then
+      INITRD="${i}"
+      break
+    fi
+  done
+
+  LINUX=
+  if test -n "${initrd_early}" || test -n "${INITRD}"; then
+    initrd="${initrd_early} ${INITRD}"
+
+    initrd_display=
+    for i in ${initrd}; do
+      initrd_display="${initrd_display} ${dirname}/${i}"
+    done
+  fi
+  LINUX=`make_system_path_relative_to_its_root $linux`
+  INITRD=`make_system_path_relative_to_its_root $initrd_display`
+  break
+done
+}
+
 get_linux_image()
 {
     arch="$1"
@@ -213,41 +314,25 @@ linux_root_device_thisversion="${LINUX_ROOT_DEVICE}"
 echo "submenu 'Deepin Rollback Advance Options' \$menuentry_id_option 'gnulinux-advanced-${boot_device_id}' {"
 for rollback in "${rollbackList[@]}"
 do
-    SNAPSHOT_DIR="${SNAPSHOT_DIR_PREFIX}/${rollback}"
+    type=`${UPGRADER} --action=type --version=${rollback}`
+
     LINUX=
-    get_linux_image "${machine}" "${SNAPSHOT_DIR}"
-    if [ "x${LINUX}" = "x" ]; then
-        echo "# not found linux image in ${SNAPSHOT_DIR}"
-        continue
-    fi
-    basename=`basename $LINUX`
-    dirname=`dirname $LINUX`
-    dtbo_dirname=`dirname $dirname`
-    dtbo_rel_dirname=`make_system_path_relative_to_its_root $dtbo_dirname`
-
-    rel_dirname=`make_system_path_relative_to_its_root $dirname`
-    version=`echo $basename | sed -e "s,^[^0-9]*-,,g"`
-    alt_version=`echo $version | sed -e "s,\.old$,,g"`
-
-    if test -e "$dtbo_dirname/dtbo.img"; then
-	    dtbo=1
-    fi
-
     INITRD=
-    if test -e "${SNAPSHOT_DIR}/initrd.img-${version}"; then
-	    INITRD="${rel_dirname}/initrd.img-${version}"
-    elif  test -e "${SNAPSHOT_DIR}/initrd.img-${alt_version}";then
-        INITRD="${rel_dirname}/initrd.img-${alt_version}"
+    if [ ${type} = ${ATOMIC} ] ; then
+        SNAPSHOT_DIR="${SNAPSHOT_DIR_PREFIX}/${rollback}"
+	LINUX=
+        get_linux_image "${machine}" "$SNAPSHOT_DIR"
+        if [ "x$LINUX" = "x" ] ; then
+            continue
+        fi
+        get_vmlinux_initrd $LINUX
+        echo "# not found linux image in ${snap_shot_dir}"
+    else
+        get_default_vmlinux_initrd
     fi
-    LINUX=${rel_dirname}/${basename}
-    # for i in "${SNAPSHOT_DIR}/initrd.img-${version}" "${SNAPSHOT_DIR}/initrd.img-${alt_version}"; do
-    #     if test -e "$i"; then
-    #         INITRD="$i"
-    #         break
-    #     fi
-    # done
+
     menu_entry=$(printf "$(gettext -d deepin-upgrade-manager 'Rollback to %s')" "${rollback}")
     submenu_indentation="$grub_tab"
-    linux_entry "$menu_entry" "${LINUX}" "${INITRD}" "${GRUB_CMDLINE_LINUX} ${GRUB_CMDLINE_LINUX_DEFAULT} back_version=${rollback}"
+    linux_entry "$menu_entry" "${LINUX}" "${INITRD}" "${GRUB_CMDLINE_LINUX} ${GRUB_CMDLINE_LINUX_DEFAULT} back_version=${rollback} back_type=${type}"
 done
 echo "}"
